import 'package:hive/hive.dart';
import 'package:random_quote/feature/quote/domain/entities/quote_model.dart';
// Note: This file will be generated by build_runner


@HiveType(typeId: 0) // Unique ID for this model in Hive
class QuoteModel {
  @HiveField(0)
  final String q; // The quote text
  @HiveField(1)
  final String a; // The author

  QuoteModel({required this.q, required this.a});
  // ... existing factory and toEntity() methods ...
 factory QuoteModel.fromJson(Map<String, dynamic> json) {
    return QuoteModel(
      q: json['q'] as String,
      a: json['a'] as String,
    );
  }

  // Mapper function to convert Model to Entity
  QuoteEntity toEntity() {
    return QuoteEntity(
      text: q,
      author: a,
    );
  }
}